# Generated by Django 5.0 on 2024-12-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="closing_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
